site_name: vectorspace.xyz
theme:
  name: material
  custom_dir: overrides
  favicon: img/Tux.png
  logo: img/Tux.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.footer
    # - navigation.sections
  palette:
    primary: white 
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - footnotes
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/vectorspacexyz
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/vectorspacexyz
plugins:
  - blog
#   - social:
#       cards: true
#   # - blog


